project 'AFN源码.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AFN源码' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AFN源码
pod 'AFNetworking'
end
